name: googleauth

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: google-github-actions/auth@v2.0.0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

