name: DeploymentWorkflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main
      - ts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
              # npm i --omit=optional --omit=dev --legacy-peer-deps
            # npm i --omit=optional --omit=prod --legacy-peer-deps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            cd /var/www/html/dev/planet # Specify the path to your app directory on the server
            git remote add origin2 https://github.com/amaurypichat/planet.git
            nvm use 20
            NODE_OPTIONS=--max_old_space_size=2000
            npm i --legacy-peer-deps
            git pull origin ts
            npm run build

