name: CI
on: push
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
            node-version: 18
      - run: npm install --legacy-peer-deps
      - name: Test Code
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          CI: "true"
        with:
          args: npm run test